#ifndef DECKARD_STRINGS_H
#define DECKARD_STRINGS_H

/* String pool for modules linked in extra / deckard_ps2m (Deckard-safe .rodata). */

extern const char deckard_str_fmt_d[];
extern const char deckard_str_fmt_u[];
extern const char deckard_str_fmt_s[];
extern const char deckard_str_fmt_min_sec[];
extern const char deckard_str_fmt_s_dash_s[];
extern const char deckard_str_fmt_watch_summary[];
extern const char deckard_str_fmt_watch_n[];
extern const char deckard_str_fmt_address_colon_s[];
extern const char deckard_str_fmt_label_colon_s[];
extern const char deckard_str_fmt_type_colon_s[];
extern const char deckard_str_fmt_display_colon_s[];
extern const char deckard_str_fmt_value_colon_s[];
extern const char deckard_str_fmt_neg_fixed[];
extern const char deckard_str_fmt_pos_fixed[];
extern const char deckard_str_fmt_addr_value[];
extern const char deckard_str_fmt_theatre_keyframe_set[];
extern const char deckard_str_fmt_duration[];
extern const char deckard_str_fmt_wait_frames[];
extern const char deckard_str_fmt_keyframes_count[];

extern const char deckard_str_ghost_reset_delete_line1[];
extern const char deckard_str_ghost_reset_delete_line2[];
extern const char deckard_str_ghost_reset_no[];
extern const char deckard_str_ghost_reset_yes[];

extern const char deckard_str_ghost_recording_space_warn[];
extern const char deckard_str_ghost_recording_too_long[];

extern const char deckard_str_font_burger_parody[];

extern const char deckard_str_skin_hue_fmt[];
extern const char deckard_str_skin_sat_fmt[];
extern const char deckard_str_skin_light_fmt[];
extern const char deckard_str_skin_sec_body[];
extern const char deckard_str_skin_sec_belly[];
extern const char deckard_str_skin_sec_wing[];
extern const char deckard_str_skin_sec_wingbone[];
extern const char deckard_str_skin_sec_horns[];
extern const char deckard_str_skin_sec_crest[];
extern const char deckard_str_skin_sec_eyes[];
extern const char deckard_str_skin_save[];
extern const char deckard_str_skin_default_section[];
extern const char deckard_str_skin_default_hue[];
extern const char deckard_str_skin_default_sat[];
extern const char deckard_str_skin_default_light[];

extern const char deckard_str_theatre_interp_ease_in_out[];
extern const char deckard_str_theatre_interp_linear[];
extern const char deckard_str_theatre_interp_catmull[];
extern const char deckard_str_theatre_interp_ease_in[];
extern const char deckard_str_theatre_interp_ease_out[];
extern const char deckard_str_theatre_autoplay_off[];
extern const char deckard_str_theatre_autoplay_fwd[];
extern const char deckard_str_theatre_autoplay_back[];
extern const char deckard_str_theatre_title[];
extern const char deckard_str_theatre_place_keyframes[];
extern const char deckard_str_theatre_start_playback[];
extern const char deckard_str_theatre_loop_on[];
extern const char deckard_str_theatre_loop_off[];
extern const char deckard_str_theatre_hide_hud_on[];
extern const char deckard_str_theatre_hide_hud_off[];
extern const char deckard_str_theatre_green_on[];
extern const char deckard_str_theatre_green_off[];
extern const char deckard_str_theatre_clear_keyframes[];
extern const char deckard_str_theatre_exit[];
extern const char deckard_str_theatre_ui_dash[];
extern const char deckard_str_theatre_x_select[];
extern const char deckard_str_theatre_end_square_back[];
extern const char deckard_str_theatre_triangle_save[];
extern const char deckard_str_theatre_keyframes_cleared[];

extern const char deckard_str_watch_type_u8[];
extern const char deckard_str_watch_type_u16[];
extern const char deckard_str_watch_type_u32[];
extern const char deckard_str_watch_type_s8[];
extern const char deckard_str_watch_type_s16[];
extern const char deckard_str_watch_type_s32[];
extern const char deckard_str_watch_type_fixed[];
extern const char deckard_str_watch_fmt_dec[];
extern const char deckard_str_watch_fmt_hex[];
extern const char deckard_str_watch_title[];
extern const char deckard_str_watch_add[];
extern const char deckard_str_watch_clear_all[];
extern const char deckard_str_watch_back[];
extern const char deckard_str_watch_controls_list[];
extern const char deckard_str_watch_duplicate[];
extern const char deckard_str_watch_remove[];
extern const char deckard_str_watch_enabled_on[];
extern const char deckard_str_watch_enabled_off[];
extern const char deckard_str_watch_controls_slot[];
extern const char deckard_str_watch_controls_circle[];
extern const char deckard_str_watch_edit_title[];
extern const char deckard_str_watch_label_edit_title[];
extern const char deckard_str_watch_edit_0x[];
extern const char deckard_str_watch_edit_controls[];
extern const char deckard_str_watch_x_save_circle_back[];
extern const char deckard_str_watch_label_none[];
extern const char deckard_str_watch_triangle_reset_label[];

extern const char deckard_str_spin_r3[];
extern const char deckard_str_spin_selected[];
extern const char deckard_str_spin_release[];
extern const char deckard_str_spin_move_stick[];
extern const char deckard_str_spin_test_opt1[];
extern const char deckard_str_spin_test_opt2[];
extern const char deckard_str_spin_test_opt3[];
extern const char deckard_str_spin_test_opt4[];
extern const char deckard_str_spin_opt_one[];
extern const char deckard_str_spin_opt_two[];
extern const char deckard_str_spin_opt_three[];
extern const char deckard_str_spin_opt_four[];

extern const char deckard_str_hitbox_menu_off[];
extern const char deckard_str_hitbox_menu_on[];

extern const char GHOSTS_DISABLED_TEXT[];
extern const char GHOSTS_ENABLED_TEXT[];
extern const char VISUAL_SPYRO_TEXT[];
extern const char VISUAL_SPYRO_WIREFRAME_TEXT[];
extern const char VISUAL_POLYGON_TEXT[];
extern const char RESET_ALL_GHOSTS_TEXT[];
extern const char SHOW_RECORDING_LENGTH_ON_TEXT[];
extern const char SHOW_RECORDING_LENGTH_OFF_TEXT[];

extern const char deckard_str_ghost_dbg_title[];
extern const char deckard_str_ghost_dbg_new_best_1[];
extern const char deckard_str_ghost_dbg_new_best_0[];
extern const char deckard_str_ghost_dbg_ga_act[];
extern const char deckard_str_ghost_dbg_ga_rec[];
extern const char deckard_str_ghost_dbg_ga_curfrm[];
extern const char deckard_str_ghost_dbg_gb_act[];
extern const char deckard_str_ghost_dbg_gb_rec[];
extern const char deckard_str_ghost_dbg_gb_curfrm[];
extern const char deckard_str_ghost_dbg_il_1[];
extern const char deckard_str_ghost_dbg_il_0[];
extern const char deckard_str_ghost_dbg_instafly_1[];
extern const char deckard_str_ghost_dbg_instafly_0[];
extern const char deckard_str_ghost_dbg_regfly_1[];
extern const char deckard_str_ghost_dbg_regfly_0[];
extern const char deckard_str_ghost_dbg_levelid[];
extern const char deckard_str_ghost_dbg_upd_calls[];
extern const char deckard_str_ghost_dbg_upd_drgskip[];
extern const char deckard_str_ghost_dbg_rec_calls[];
extern const char deckard_str_ghost_dbg_start_calls[];
extern const char deckard_str_ghost_dbg_start_insta[];
extern const char deckard_str_ghost_dbg_start_reg[];
extern const char deckard_str_ghost_dbg_hdr_a_w02[];
extern const char deckard_str_ghost_dbg_hdr_a_w35[];
extern const char deckard_str_ghost_dbg_hdr_b_w02[];
extern const char deckard_str_ghost_dbg_hdr_b_w35[];
extern const char deckard_str_ghost_dbg_a_log_fc[];
extern const char deckard_str_ghost_dbg_a_log_ft[];
extern const char deckard_str_ghost_dbg_a_log_lv[];
extern const char deckard_str_ghost_dbg_b_log_fc[];
extern const char deckard_str_ghost_dbg_b_log_ft[];
extern const char deckard_str_ghost_dbg_b_log_lv[];
extern const char deckard_str_ghost_dbg_f0_dx[];
extern const char deckard_str_ghost_dbg_f0_dy[];
extern const char deckard_str_ghost_dbg_f0_dz[];
extern const char deckard_str_ghost_dbg_ds_23afc[];
extern const char deckard_str_ghost_dbg_ds_23b00[];
extern const char deckard_str_ghost_dbg_ga_posx[];

extern const char deckard_str_boot_hs_title[];
extern const char deckard_str_boot_hs_addr[];
extern const char deckard_str_boot_hs_row[];
extern const char deckard_str_boot_hs_phase[];
extern const char deckard_str_boot_hs_lbl_magic[];
extern const char deckard_str_boot_hs_lbl_ver[];
extern const char deckard_str_boot_hs_lbl_flg[];
extern const char deckard_str_boot_hs_lbl_lvl[];
extern const char deckard_str_boot_hs_lbl_r0[];
extern const char deckard_str_boot_hs_lbl_r1[];
extern const char deckard_str_boot_hs_lbl_r2[];
extern const char deckard_str_boot_hs_lbl_r3[];

#endif /* DECKARD_STRINGS_H */
