/*
 * sym.h - generated from selected .sym symbol inputs.
 *
 * Edit symbols/default.sym to add typed game symbols.
 * This file is generated by the utility.
 */

#ifndef SYM_H
#define SYM_H

#include <types.h>
#include <symbols.h>

#ifdef __cplusplus
extern "C" {
#endif

/* No generated symbols yet. */

#ifdef __cplusplus
}
#endif

#endif // SYM_H
